services:
  # --- SERVICIO DE BASE DE DATOS ---
  db:
    image: postgres:16-alpine # Usamos la versión segura por defecto (SCRAM)
    container_name: smartinventory_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=SmartInventoryDb
    ports:
      - "5432:5432" # Exponemos el puerto por si quieres inspeccionar con pgAdmin externo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # --- SERVICIO DE API (.NET) ---
  api:
    container_name: smartinventory_api
    build:
      context: .
      dockerfile: src/SmartInventory.API/Dockerfile
    ports:
      - "8080:8080" # Mapeamos puerto 8080 del contenedor al 8080 de tu PC
    environment:
      # AQUÍ ESTÁ EL TRUCO:
      # Host=db -> Se conecta al servicio 'db' definido arriba.
      # Usamos __ (doble guion bajo) para navegar en el JSON de configuración de .NET
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SmartInventoryDb;Username=admin;Password=adminpassword
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db # Espera a que la DB inicie antes de intentar arrancar la API
    restart: on-failure

  # --- PGADMIN (Opcional, para ver los datos) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: smartinventory_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
