services:
  # --- SERVICIO DE BASE DE DATOS ---
  db:
    image: postgres:16-alpine
    container_name: smartinventory_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=SmartInventoryDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # --- SERVICIO DE API (.NET) ---
  api:
    container_name: smartinventory_api
    build:
      context: .
      dockerfile: src/SmartInventory.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SmartInventoryDb;Username=admin;Password=adminpassword
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Secret=EstaEsUnaClaveSecretaMuyLargaParaDesarrollo123!
      - JwtSettings__Issuer=SmartInventory
      - JwtSettings__Audience=SmartInventoryUsers
    depends_on:
      - db
    restart: on-failure

  # --- PGADMIN ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: smartinventory_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
